//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centric.SkillSurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Centric.SkillSurvey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW dbo.[Resource] AS
        ///SELECT
        ///  r.ResourceUID
        ///, r.EmployerDesc
        ///, r.CentricEmployerFlag
        ///, r.FirstName
        ///, r.LastName 
        ///, r.ResourceLabel
        ///, r.EmailAddress
        ///, r.CreateTimestamp
        ///, r.ModifyTimestamp
        ///FROM
        ///(
        ///  SELECT rs.*
        ///  , ROW_NUMBER() OVER (
        ///      PARTITION BY rs.ResourceUID
        ///      ORDER BY rs.SnapshotTimestamp DESC) AS FilterIndex
        ///  FROM
        ///  dbo.[ResourceSnapshot] rs
        ///) r
        ///WHERE
        ///r.FilterIndex = 1
        ///;.
        /// </summary>
        internal static string CreateViewResource {
            get {
                return ResourceManager.GetString("CreateViewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW dbo.SurveyResponse AS
        ///SELECT
        ///  rs.ResourceUID
        ///, rs.SkillUID
        ///, rs.AspectUID
        ///, rs.Ratingvalue
        ///, rs.SnapshotTimestamp
        ///FROM
        ///(
        ///  SELECT
        ///    rsx.*
        ///  , ROW_NUMBER() OVER (
        ///      PARTITION BY rsx.ResourceUID, rsx.SkillUID, rsx.AspectUID
        ///      ORDER BY rsx.SnapshotTimestamp Desc) AS FilterIndex
        ///  FROM
        ///  dbo.ResourceSurveySnapshot rsx
        ///
        ///) rs
        ///WHERE
        ///rs.FilterIndex = 1
        ///;.
        /// </summary>
        internal static string CreateViewSurveyResponse {
            get {
                return ResourceManager.GetString("CreateViewSurveyResponse", resourceCulture);
            }
        }
    }
}
